package Forms;

import DAO.BitacoraERPDAO;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author md
 */
public class dlgBitacora extends javax.swing.JDialog {
    private TableRowSorter<TableModel> sorter;

    /**
     * Creates new form dlgBitacora
     * @param parent
     * @param modal
     */
    public dlgBitacora(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        ftFecha.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        tblBitacora.setModel( buildTableModel() );
        setTableBitacoraSorter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBitacora = new javax.swing.JTable();
        ftFecha = new javax.swing.JFormattedTextField();
        lblFecha = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bitácora");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setLocation(new java.awt.Point(200, 200));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));

        tblBitacora.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblBitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBitacora);

        ftFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        ftFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftFecha.setText("00/00/0000");
        ftFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFecha.setText("Fecha:");

        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFecha)
                        .addGap(18, 18, 18)
                        .addComponent(ftFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltrar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha)
                    .addComponent(btnFiltrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        RowFilter<TableModel, Integer> rf = null;
        try {
            rf = RowFilter.regexFilter(ftFecha.getText(), 0);
        } catch (java.util.regex.PatternSyntaxException pse) {
            JOptionPane.showMessageDialog(null, "Formato de fecha no válido.");
        }
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_btnFiltrarActionPerformed
    
    private DefaultTableModel buildTableModel() {
        try {
            ResultSet rs = BitacoraERPDAO.consultarBitacora();
            // metadata from ResultSet
            ResultSetMetaData metaData = rs.getMetaData();
            
            // names of columns
            Vector<String> columnNames = new Vector<>();
            int columnCount = metaData.getColumnCount();
            for (int column = 1; column <= columnCount; column++) {
                columnNames.add( metaData.getColumnName( column ) );
            }

            // data of the table
            Vector<Vector<Object>> data = new Vector<>();
            while ( rs.next() ) {
                Vector<Object> vector = new Vector<>();
                for ( int columnIndex = 1; columnIndex <= columnCount; columnIndex++ ) {
                    vector.add( rs.getObject( columnIndex ) );
                }
                data.add( vector );
            }            
            return new DefaultTableModel( data, columnNames );
        } catch ( SQLException ex ) {
            System.err.println( ex.getMessage());
            return new DefaultTableModel();
        }
    }
    
    private void setTableBitacoraSorter() {
        sorter = new TableRowSorter<>( tblBitacora.getModel() );
        
        Comparator<Timestamp> comparator = new Comparator<Timestamp>() {
            @Override
            public int compare(Timestamp o1, Timestamp o2) {
                return o1.compareTo(o2);
            }
        };
        sorter.setComparator(5, comparator);
        sorter.setRowFilter(RowFilter.regexFilter(ftFecha.getText()));
        tblBitacora.setRowSorter(sorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JFormattedTextField ftFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JTable tblBitacora;
    // End of variables declaration//GEN-END:variables
}
