package Forms;

import BO.UsuarioBO;
import DAO.UsuarioDAO;
import java.awt.Color;
import java.awt.Font;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author md
 */
public class dlgIniciarSesion extends javax.swing.JDialog {
    private boolean usuarioValidado;
    private boolean contraEscrita;
    private final UsuarioBO usuario;
    private final Font placeHolderFont, userInputFont;
    private final Color placeHolderFontColor, userInputFontColor;
    
    /**
     * Creates new form dlgIniciarSesion
     * @param parent
     * @param modal
     */
    public dlgIniciarSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        usuarioValidado = false;
        contraEscrita = false;
        usuario = new UsuarioBO();
        placeHolderFont = new Font("Segoe UI", 2, 14);
        placeHolderFontColor = new Color(153, 153, 153);
        userInputFont = new Font("Segoe UI", 0, 14);
        userInputFontColor = new Color(0, 0, 0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblImagenAut = new javax.swing.JLabel();
        lblImgUsuario = new javax.swing.JLabel();
        lblImgContra = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pssContra = new javax.swing.JPasswordField();
        chkMostrarContra = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iniciar sesión");
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setLocation(new java.awt.Point(200, 200));
        setName("dlgIniciarSesion"); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar sesión");

        lblImagenAut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenAut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/usuario.png"))); // NOI18N

        lblImgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/us.png"))); // NOI18N

        lblImgContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ke.png"))); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuario.setText("Usuario");
        txtUsuario.setCaretPosition(0);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pssContra.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        pssContra.setForeground(new java.awt.Color(153, 153, 153));
        pssContra.setText("Contraseña");
        pssContra.setCaretPosition(0);
        pssContra.setEchoChar('\u0000');
        pssContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pssContraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pssContraFocusLost(evt);
            }
        });

        chkMostrarContra.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        chkMostrarContra.setForeground(new java.awt.Color(153, 153, 153));
        chkMostrarContra.setText("Mostrar");
        chkMostrarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImgUsuario)
                            .addComponent(lblImgContra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUsuario)
                            .addComponent(pssContra, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkMostrarContra))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImagenAut)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblIniciarSesion)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblImagenAut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIniciarSesion)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgContra)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pssContra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkMostrarContra)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if(verificarDatos()) {
            usuario.setNombreUsuario(txtUsuario.getText());
            usuario.setHashContra(util.SHA1.cifrarContra(charArrayToString(pssContra.getPassword()).trim()));
            UsuarioDAO.ValidarUsuario(usuario);
            
            //Checar si el usuario fue validado
            //La Id -1 se asigna a usuarios no válidos
            if( usuario.getIdUsuario() != -1 ) {
                usuarioValidado = true;
                limpiarCampos();
                this.dispose();
            } else {
                usuarioValidado = false;
                JOptionPane.showMessageDialog(this, "El usuario no existe.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese los datos necesarios.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        usuario.setIdUsuario(-1);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if ( txtUsuario.getText().equals("Usuario") ) {
            txtUsuario.setText("");
            txtUsuario.setFont(userInputFont);
            txtUsuario.setForeground(userInputFontColor);
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if ( txtUsuario.getText().equals("") ) {
            txtUsuario.setText("Usuario");
            txtUsuario.setFont(placeHolderFont);
            txtUsuario.setForeground(placeHolderFontColor);
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void pssContraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pssContraFocusGained
        if ( charArrayToString(pssContra.getPassword()).equals("Contraseña") ) {
            pssContra.setEchoChar('\u25cf'); // Unicode black circle (U+25CF)
            pssContra.setText("");
            pssContra.setFont(userInputFont);
            pssContra.setForeground(userInputFontColor);
        }
    }//GEN-LAST:event_pssContraFocusGained

    private void pssContraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pssContraFocusLost
        if ( charArrayToString(pssContra.getPassword()).equals("") ) {
            pssContra.setEchoChar('\u0000'); // Unicode null (U+0000)
            pssContra.setText("Contraseña");
            pssContra.setFont(placeHolderFont);
            pssContra.setForeground(placeHolderFontColor);
        }
    }//GEN-LAST:event_pssContraFocusLost

    private void chkMostrarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarContraActionPerformed
        if ( chkMostrarContra.isSelected() ) {
            pssContra.setEchoChar('\u0000'); // Unicode null (U+0000)
        } else {
            pssContra.setEchoChar('\u25cf'); // Unicode black circle (U+25CF)
        }
        
    }//GEN-LAST:event_chkMostrarContraActionPerformed

    public boolean verificarDatos() {
        if(txtUsuario.getText().trim().equals("") || Arrays.toString(pssContra.getPassword()).trim().equals("")) {
            return false;
        }else {
            return true;
        }
    }
    
    public void limpiarCampos() {
        txtUsuario.setText("");
        pssContra.setText("");
    }
    
    private String charArrayToString( char[] input ) {
        return new String(input);
    }
    
    public boolean isUsuarioValidado() {
        return usuarioValidado;
    }
    
    public UsuarioBO getUsuario() {
        return usuario;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox chkMostrarContra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagenAut;
    private javax.swing.JLabel lblImgContra;
    private javax.swing.JLabel lblImgUsuario;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JPasswordField pssContra;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
