package Forms;

import BO.PerfilesBO;
import DAO.PerfilesDAO;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author md
 */
public class dlgPerfiles extends javax.swing.JDialog {
    private final PerfilesDAO objPerfDao;
    private final PerfilesBO objperfBO;
    private String idPerfil;
    private boolean editar;

    /**
     * Creates new form dlgPerfiles
     * @param parent
     * @param modal
     */
    public dlgPerfiles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.objperfBO = new PerfilesBO();
        this.objPerfDao = new PerfilesDAO();
        editar = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePerfiles = new JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };
        jLabel2 = new javax.swing.JLabel();
        txtNombrePerfil = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perfiles");
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setLocation(new java.awt.Point(200, 200));

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTablePerfiles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTablePerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePerfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTablePerfilesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePerfiles);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre perfil:");

        txtNombrePerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icong.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/iconca.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icond.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePerfilesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePerfilesMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int fila = jTablePerfiles.getSelectedRow();//Obtiene el indice de la fila
            if(fila >=0) {//Verifica que se haya seleccionado una fila
                editar = true;//Activa la opcion de editar
                btnCancelar.setEnabled(true);//Activa el boton de cancelar
                btnBuscar.setEnabled(false);//Bloquea el boton de busar
                idPerfil = jTablePerfiles.getValueAt(fila, 0).toString();//obtiene el código del perfil
                txtNombrePerfil.setText(jTablePerfiles.getValueAt(fila, 1).toString());//Muestra el nombre del perfil seleccionado
                txtNombrePerfil.setEditable(false);
                btnEliminar.setEnabled(true);
                btnGuardar.setText("Modificar");
            }else {
                JOptionPane.showMessageDialog(null, "Porfavor seleccione una fila...");
            }
        }
    }//GEN-LAST:event_jTablePerfilesMousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if(txtNombrePerfil.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Error! porfavor ingrese el nomnre del perfil");
        }else {
            if(editar == false) {
                if(Guardar()) {
                    JOptionPane.showMessageDialog(null, "Registro agregado correctamente!!!");
                    Listado("", 0);//Actualiza los registros que se muestran
                    resetearEstadoComponentes();
                }else {
                    JOptionPane.showMessageDialog(null, "Ocurrió un error al agregar el perfil!");
                }
            }else {
                if(btnGuardar.getText().trim().equals("Modificar")) {
                    txtNombrePerfil.setEditable(true);
                    txtNombrePerfil.requestFocus();
                    btnGuardar.setText("Guardar");
                }else {
                    if(Modificar()) {
                        JOptionPane.showMessageDialog(null, "Registro modificado correctamente!!!");
                        Listado("", 0);//Actualiza los registros que se muestran
                        resetearEstadoComponentes();
                    }else {
                        JOptionPane.showMessageDialog(null, "Ocurrió un error al modificar el perfil!");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        resetearEstadoComponentes();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(txtNombrePerfil.getText().equals("")) {
            Listado("", 0);//Trae todos los registros
        }else {
            objperfBO.setNombrePerfil(txtNombrePerfil.getText().trim());
            Listado(objperfBO.getNombrePerfil(), 1);//Trae un solo registro
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar el registro seleccionado?");
        if(JOptionPane.OK_OPTION == resp) {
            if(Eliminar(Integer.parseInt(idPerfil))) {//Obtiene el id para eliminar
                JOptionPane.showMessageDialog(null, "Datos eliminados correctamente!!!");
                resetearEstadoComponentes();
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrrió un error al eliminar el registro");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    public void resetearEstadoComponentes() {
        editar = false;
        btnBuscar.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnGuardar.setEnabled(true);
        idPerfil = "";
        txtNombrePerfil.setText("");
        txtNombrePerfil.setEditable(true);
        txtNombrePerfil.requestFocus();
        btnGuardar.setText("Guardar");
        btnEliminar.setEnabled(false);
        Listado("", 0);
    }
    
    public void Listado(String perfil, int codigo) {
        ResultSet result;
        try{
            result = objPerfDao.Lista(perfil, codigo);
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTablePerfiles.setModel(modelo);
            
            java.sql.ResultSetMetaData mtDatos = result.getMetaData();
            int numColumn = mtDatos.getColumnCount();
            Object[] nomCampos = new Object[numColumn];
            for(int i = 0; i < numColumn; i++) {
                nomCampos[i] = mtDatos.getColumnLabel(i+1);
            }
            modelo.setColumnIdentifiers(nomCampos);
            while(result.next()) {
                Object[] fila = new Object[numColumn];
                for(int j = 0; j < numColumn; j++) {
                    fila[j] = result.getObject(j+1);
                }
                modelo.addRow(fila);
            }
            result.close();
        }catch(Exception err) {
            System.out.println("Error! no hay nada en la base de datos...");
        }
    }
    
    public boolean Guardar() {
        try{
            objperfBO.setNombrePerfil(txtNombrePerfil.getText().trim());
            
            objPerfDao.AgregarPerfil(objperfBO);
            return true;
        }catch(Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error! Puede que el código ya esté registrado...");
            return false;
        }
    }
    
    public boolean Modificar() {
        try{
            objperfBO.setIdPerfil(Integer.parseInt(idPerfil));
            objperfBO.setNombrePerfil(txtNombrePerfil.getText().trim());
            
            objPerfDao.ModificarPerfil(objperfBO);
            return true;
        }catch(Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error!...");
            return false;
        }
    }
    public boolean Eliminar(int codPerfil) {
        try{
            objperfBO.setIdPerfil(codPerfil);
            
            objPerfDao.EliminarPerfil(objperfBO);
            return true;
        }catch(Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error!...");
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePerfiles;
    private javax.swing.JTextField txtNombrePerfil;
    // End of variables declaration//GEN-END:variables
}
